# Basic config
baseURL = "https://blog.rsinha.org"
languageCode = 'en-gb'
theme = "typo"
title='Ritesh is Rambling'
copyright = "Ritesh Sinha"


[taxonomies]
tag = 'tags'

[params]
  # The description of your website
description = "Blog blog"
paginationSize = 25
theme = 'auto'
colorPalette = 'catpuccin'
hideHeader = 'true'
# The path to your favicon
favicon = "images/favicon.png"
listdateFormat = "2 Jan 2006"
# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'


[[params.social]]
name = "github"
url = "https://github.com/ritesh"

[[params.social]]
name = "linkedin"
url = "mailto:r@example.org"
